<?php

	include_once 'vacency_project/show_report.php'; 
	include_once 'common_functions.php'; 
	// echo "<pre>";
	// print_r($printable_array);
	// echo "</pre>";

?>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Greefi Technologies</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <script type="text/javascript" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
 <!--  <script async="true" src="https://static.optinchat.com/optinchat.js" id="oc_script" convid="tD7OBwUTKDh4v4R8zRWy7rZ3Pbx2"></script> -->


   <!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-92345002-1', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
</head>
<body>

<div class="jumbotron text-center">
<img src="logo.png" style="height: 100px;">
  <h1>Greefi Technologies</h1>
  <p>We do products that impact every day work &#128526; </p> 
  <p style="font-size: 16px;">We have implemented an analytic tool for Colleges loacted in Salem, Namakkal surroundings, These Data has been generated by <b><a href="http://vacancy.tnea.ac.in/" target="_blank">TNEA</a></b> @ 2017 content</p>
  <p style="font-size: 14px;">Based on user's request, We have published in our main page</p>
</div>


<div class="container">
	
	<div class="alert alert-info">
	  <strong>Info:- </strong> Having initial database?, drop us a mail we will give the report. Trust us we will not share your details. <a mailto:"info@greefitech.com">info@greefitech.com</a>
	</div>

	<div class="alert alert-success">
	  Need updates in SMS for <strong>Free</strong>? Drop your details, We will contact you soon :)
	</div>

	<table class="table table-hover text-center" id="myTable">
		<thead>
			<tr>
				<th class="text-center">College Name</th>
				<th class="text-center">Over All (Admission)Percentage</th>
				<th class="text-center">Total Government Quota Seat</th>
				<th class="text-center">Todays Admission</th>
				<th class="text-center">Over All Admission</th>
			</tr>
		</thead>
		<tbody>
			<?php 
				foreach ($printable_array as $key => $college_details) {
					$percentage = $college_details['percentage'];
					unset($college_details['percentage']);
					foreach ($college_details as $college_name => $department_details) {
						$content = "<tr onclick=\"document.location = 'show_data.php?key=".$key."';\"><td>".get_college_name($college_name)."</td><td>$percentage %</td><td>".$department_details['grand_total']['total']."</td><td>".$department_details['grand_total']['today']."</td><td>".$department_details['grand_total']['overall']."</td></tr>";
						echo $content;
					}
				}
			?>
		</tbody>
	</table>
</div>
<footer>
<br>
	<p class="text-center">
		Made with &#128149; <a href="#">Greefi Tech</a>  Reach us :- <b>9842972047</b>
	</p>
</footer>

<style type="text/css">
	tr { cursor: pointer; cursor: hand; }
</style>

<script>
$('#myTable').dataTable( {
  "pageLength": 15,
  "lengthMenu": [[5, 10, 15, 30, -1], [5, 10, 15, 30, 'All']],
  "aaSorting": [[3, "desc"]]
} );
</script>

</body>
</html>